version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: qortex-db
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: qortex
      MYSQL_PASSWORD: secret
    volumes:
      - /mysql:/var/lib/mysql
    networks:
      - qortex_network

  app:
    build:
      dockerfile: Dockerfile
    container_name: qortex_app
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: qortex
      DB_USERNAME: root
      DB_PASSWORD: secret
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      - qortex_network
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    container_name: qortex_nginx
    volumes:
      - ./src:/var/www
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "8080:80"
    networks:
      - qortex_network
    depends_on:
      - app

volumes:
  mysql:


networks:
  qortex_network:
